// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System;


public class EnemyControl : BaseCharacterControl
{
	public Transform target;


	// Use this for initialization
	void Start () {
		StartBase();
		moveSpeed = 0.04f;
	}
	
	void Update() {
		MoveLeftRight(Math.Sign(target.position.x - transform.position.x));
	}
	
}


