// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System;


public class EnemyControl : BaseCharacterControl
{
	// UnityChan
	public Transform target;

	// Use this for initialization
	void Start () {
		StartBase();
		moveSpeed = 0.04f;
	}
	
	void Update() {
		state.KeyLeftRight(Math.Sign(target.position.x - transform.position.x));
		state.KeyUpDown(Math.Sign(target.position.y - transform.position.y));

		animator.SetBool("isgrounded", !state.IsFalling());
		animator.SetFloat("speed", state.IsMovingLeftRight() ? 0.3f : 0f);

		state.Tick();
	}
}

