// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

public static class Global
{
	public static int stage = 1;
	public static int score = 0;
	public static bool paused = false;
	public static string stageUrl = "http://mokemokechicken.github.io/UnityChanRoadRunnerStageData";

	private static StageController stageController_;
	public static StageController stageControler 
	{
		get { return stageController_; }
		set { stageController_ = value; }
	}
}
