// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

public class Tag {
	public const string LADDER = "Ladder";
	public const string BAR = "Bar";
	public const string BLOCK = "Block";
	public const string BEAM = "Beam";
}
