// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

public class TreasureControl : MonoBehaviour
{
	public void HitWithPlayer() {
		Destroy(gameObject.transform.parent.gameObject);
		Global.stageControler.PlayerGotTreasure();
	}

	void OnTriggerEnter(Collider other) {
		if (other.gameObject.tag == Tag.PLAYER) {
			HitWithPlayer();
		}
	}
}
